### ISSUE TITLE
Checklist: normalise topics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/kotlin#297]
**Note**: the suggestions are generated automagically. If something is _actually_ missing, please open an issue at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topics.

```
=> fetching config from ../exercism-kotlin/config.json
=> reading topics from ..\problem-specifications\TOPICS.txt
```

<details>
  <summary>List of valid topics</summary>

  - `abstract_classes`
  - `callbacks`
  - `conditionals`
  - `events`
  - `equality`
  - `exception_handling`
  - `generics`
  - `inheritance`
  - `interfaces`
  - `loops`
  - `operator_overloading`
  - `pattern_matching`
  - `polymorphism`
  - `recursion`
  - `threading`
  - `type_conversion`
  - `variables`
  - `arrays`
  - `booleans`
  - `classes`
  - `dates`
  - `discriminated_unions`
  - `enumerations`
  - `floating_point_numbers`
  - `graphs`
  - `integers`
  - `lists`
  - `maps`
  - `matrices`
  - `optional_values`
  - `queues`
  - `records`
  - `sequences`
  - `sets`
  - `stacks`
  - `strings`
  - `structs`
  - `time`
  - `trees`
  - `tuples`
  - `algorithms`
  - `bitwise_operations`
  - `concurrency`
  - `cryptography`
  - `domain_specific_languages`
  - `files`
  - `filtering`
  - `games`
  - `globalization`
  - `logic`
  - `math`
  - `memory_management`
  - `networking`
  - `parallelism`
  - `parsing`
  - `pattern_recognition`
  - `performance`
  - `randomness`
  - `refactoring`
  - `regular_expressions`
  - `searching`
  - `security`
  - `sorting`
  - `text_formatting`
  - `transforming`
  - `behavior_driven_development`
  - `functional_programming`
  - `object_oriented_programming`
  - `reactive_programming`
  - `test_driven_development`
</details>

## Exercises with non-standard topics

- [x] [`leap`](https://github.com/exercism/kotlin/tree/master/exercises/leap)
  Incorrect topics:
  - [ ] `control_flow_if_else_statements` (perhaps: `conditionals`)
- [ ] [`sublist`](https://github.com/exercism/kotlin/tree/master/exercises/sublist)
  Incorrect topics:
  - [ ] `enumeration` (perhaps: `enumerations`)
- [x] [`react`](https://github.com/exercism/kotlin/tree/master/exercises/react)
  Incorrect topics:
  - [ ] `higher_order_functions` (perhaps: `functional_programming`)
  - [ ] `nested_classes` (perhaps: `classes`)

## Exercises without topics

- [ ] [`accumulate`](https://github.com/exercism/kotlin/tree/master/exercises/accumulate)
- [ ] [`binary`](https://github.com/exercism/kotlin/tree/master/exercises/binary)
- [ ] [`hexadecimal`](https://github.com/exercism/kotlin/tree/master/exercises/hexadecimal)
- [ ] [`strain`](https://github.com/exercism/kotlin/tree/master/exercises/strain)

**Comment by dector** [comment]
[It's](https://tracks.exercism.io/kotlin/master/topics) gonna be green now!
