### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/kotlin#451]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/kotlin/issues/442)
- [ ] [Add key features](https://github.com/exercism/kotlin/issues/443)
- [ ] [Add tags](https://github.com/exercism/kotlin/issues/444)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/kotlin/issues/445)
- [ ] [Update status of track](https://github.com/exercism/kotlin/issues/449)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/kotlin/issues/450)
- [ ] [Pass linting checks](https://github.com/exercism/kotlin/issues/446)
- [ ] [Build Test Runner](https://github.com/exercism/kotlin/issues/447)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/kotlin/issues/448) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/kotlin/issues/455)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
